name: Autograding Quiz

on: [push]

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - name: Repo ophalen
        uses: actions/checkout@v3

      - name: Node installeren
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Dependencies installeren
        run: npm install

      - name: Tests uitvoeren
        run: npm test
